name: gogithub
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_vector_icons: ^0.2.1
  cupertino_icons: ^0.1.2
  flutter_highlight: ^0.6.0
  flutter_markdown: ^0.3.3

  intl: ^0.16.0
  dio: ^3.0.3
  provider: ^4.3.2+1
  file_icon: ^0.3.0
  filesize: ^1.0.4
  shared_preferences: ^0.5.10
  share: ^0.6.0
  cached_network_image: ^2.1.0
  fluttertoast: ^4.0.0
  flukit: ^1.0.2
  fimber: ^0.4.4

  url_launcher: ^5.4.1
  uri: ^0.11.3
  uni_links: ^0.2.0
  launch_review: ^2.0.0

  primer: ^0.0.2
  fluro: ^1.5.1
  nanoid: ^0.0.6
  github: ^7.0.2
  artemis: ^5.1.0
  github_trending: ^0.2.0

  gql_link: ^0.2.0
  tuple: ^1.0.2
  timeago: ^2.0.18
  package_info: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_to_model: ^1.3.13
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
#  source_gen: ^0.9.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - imgs/
      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware.

      # For details regarding adding assets from package dependencies, see
      # https://flutter.dev/assets-and-images/#from-packages

      # To add custom fonts to your application, add a fonts section here,
      # in this "flutter" section. Each entry in this list should have a
      # "family" key with the font family name, and a "fonts" key with a
      # list giving the asset and other descriptors for the font. For
      # example:
  fonts:
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
        - asset: fonts/FiraCode-Bold.ttf
          weight: 700
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700
    - family: PT Mono
      fonts:
        - asset: fonts/PTMono-Regular.ttf
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-RegularItalic.ttf
          style: italic
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Ubuntu Mono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-RegularItalic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Cascadia Code
      fonts:
        - asset: fonts/Cascadia.ttf
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-Bold-Italic.ttf
          style: italic
          weight: 700
